object Form_Settings: TForm_Settings
  Left = 0
  Top = 0
  Align = alCustom
  BorderIcons = []
  BorderStyle = bsSingle
  Caption = 'Settings'
  ClientHeight = 422
  ClientWidth = 569
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsMDIChild
  OldCreateOrder = False
  Position = poDesigned
  Visible = True
  OnActivate = FormActivate
  PixelsPerInch = 96
  TextHeight = 13
  object GroupBox1: TGroupBox
    Left = 8
    Top = 8
    Width = 553
    Height = 409
    Color = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentBackground = False
    ParentColor = False
    ParentFont = False
    TabOrder = 0
    object Label_ChooseWatcher: TLabel
      Left = 136
      Top = 6
      Width = 143
      Height = 16
      Caption = 'Choose Folder Watcher :'
      Color = clMenuHighlight
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentColor = False
      ParentFont = False
    end
    object Label_Filter: TLabel
      Left = 308
      Top = 251
      Width = 100
      Height = 18
      Caption = 'Watcher Filter :'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object Button_Start: TButton
      Left = 61
      Top = 212
      Width = 75
      Height = 25
      Cursor = crHandPoint
      Caption = 'Start'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      OnClick = Button_StartClick
    end
    object Button_Delete: TButton
      Left = 405
      Top = 212
      Width = 75
      Height = 25
      Cursor = crHandPoint
      Caption = 'Delete'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      OnClick = Button_DeleteClick
    end
    object Button_Stop: TButton
      Left = 235
      Top = 212
      Width = 75
      Height = 25
      Cursor = crHandPoint
      Caption = 'Stop'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      OnClick = Button_StopClick
    end
    object Button_ShowFilter: TButton
      Left = 80
      Top = 296
      Width = 153
      Height = 36
      Cursor = crHandPoint
      Caption = 'Show Watcher filter'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      OnClick = Button_ShowFilterClick
    end
    object Memo_Filter: TMemo
      Left = 308
      Top = 275
      Width = 215
      Height = 123
      Color = clCream
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      ScrollBars = ssBoth
      TabOrder = 4
    end
    object ListBox_Folder: TListBox
      Left = 136
      Top = 28
      Width = 286
      Height = 166
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = []
      ItemHeight = 13
      ParentFont = False
      TabOrder = 5
    end
    object Button_Log: TButton
      Left = 80
      Top = 338
      Width = 153
      Height = 36
      Cursor = crHandPoint
      Caption = 'Show Name of LogFile'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 6
      OnClick = Button_LogClick
    end
  end
end
